version: '3.9'
services:

  proxy:
    image: kcisijohnny/proxy
#    build:
#      context: ./proxy/
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./proxy/conf.d/:/etc/nginx/conf.d/
      - portfolio_statics:/portfolio/staticfiles
      - middle_earth_statics:/middle_earth/staticfiles
    networks:
      - portfolio_network

  portfolio:
#    for production uncomment the line below:
    image: kcisijohnny/portfolio
    secrets:
      - portfolio_secret_key
      - debug
      - aws_access_key
      - aws_secret_key
#    for development uncomment the line below:
#    build: portfolio
#    restart: always
    ports:
      - '5000:5000'
    networks:
      - portfolio_network
    volumes:
      - ./portfolio/:/code/
      - portfolio_statics:/code/staticfiles
#    environment:
#      - DEBUG=1
#      - DJANGO_SECRET_KEY=##4cyfssb-1#wpn)cifrdc22-n-=yv-n)#7eofx7p==-ibg
#      - POSTGRES_DB=portfolio_db
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=e5runertuw54u542

  middleearthfront:
    #    for production uncomment the line below:
    image: kcisijohnny/front
    secrets:
      - front_postgres_db
      - front_postgres_user
      - front_postgres_password
      - front_secret_key
      - debug
    #    for development uncomment the line below:
#    build: middle_earth_front
#    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db_front
    networks:
      - portfolio_network
    volumes:
      - ./middle_earth_front/:/code/
      - middle_earth_statics:/code/staticfiles
#    environment:
#      - DEBUG=1
#      - DJANGO_SECRET_KEY=##4cyfssb-1#wpn)cifrdc22-n-=yv-n)#7eofx7p==-ibg
#      - POSTGRES_DB=db_front
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=e5runertuw54u542

  middleearthauth:
    #    for production uncomment the line below:
    image: kcisijohnny/auth
    secrets:
      - auth_postgres_db
      - auth_postgres_user
      - auth_postgres_password
      - auth_secret_key
      - debug
      - signing_key
      - public_key
    #    for development uncomment the line below:
#    build: middle_earth_auth
#    restart: always
    ports:
      - '8001:8001'
    depends_on:
      - db_auth
    networks:
      - portfolio_network
    volumes:
      - ./middle_earth_auth/:/code/
#    environment:
#      - DEBUG=1
#      - DJANGO_SECRET_KEY=##4cyfssb-1#wpn)cifrdc22-n-=yv-n)#7eofx7p==-ibg
#      - POSTGRES_DB=db_auth
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=e5runertuw54u542

  middleearthitems:
    #    for production uncomment the line below:
    image: kcisijohnny/items
    secrets:
      - items_postgres_db
      - items_postgres_user
      - items_postgres_password
      - items_secret_key
      - debug
    #    for development uncomment the line below:
#    build: middle_earth_items
#    restart: always
    ports:
      - '8002:8002'
    depends_on:
      - db_items
    networks:
      - portfolio_network
    volumes:
      - ./middle_earth_items/:/code/
#    environment:
#      - DEBUG=1
#      - DJANGO_SECRET_KEY=##4cyfssb-1#wpn)cifrdc22-n-=yv-n)#7eofx7p==-ibg
#      - POSTGRES_DB=db_items
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=e5runertuw54u542

  middleearthinventory:
    #    for production uncomment the line below:
    image: kcisijohnny/inventory
    secrets:
      - inventory_postgres_db
      - inventory_postgres_user
      - inventory_postgres_password
      - inventory_secret_key
      - debug
      - signing_key
      - public_key
    #    for development uncomment the line below:
#    build: middle_earth_inventory
#    restart: always
    ports:
      - '8003:8003'
    depends_on:
      - db_inventory
    networks:
      - portfolio_network
    volumes:
      - ./middle_earth_inventory/:/code/
#    environment:
#      - DEBUG=1
#      - DJANGO_SECRET_KEY=##4cyfssb-1#wpn)cifrdc22-n-=yv-n)#7eofx7p==-ibg
#      - POSTGRES_DB=db_inventory
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=e5runertuw54u542

  db_front:
    image: postgres
    secrets:
      - front_postgres_db
      - front_postgres_user
      - front_postgres_password
    restart: always
    expose:
      - "5432"
    networks:
      - portfolio_network
    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_DB=market
#      - POSTGRES_PASSWORD=e5runertuw54u542
      - POSTGRES_USER_FILE=/run/secrets/front_postgres_user
      - POSTGRES_DB_FILE=/run/secrets/front_postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/front_postgres_password
    volumes:
      - front_data:/var/lib/postgresql/data

  db_auth:
    image: postgres
    secrets:
      - auth_postgres_db
      - auth_postgres_user
      - auth_postgres_password
    restart: always
    expose:
      - "5432"
    networks:
      - portfolio_network
    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_DB=market
#      - POSTGRES_PASSWORD=e5runertuw54u542
      - POSTGRES_USER_FILE=/run/secrets/auth_postgres_user
      - POSTGRES_DB_FILE=/run/secrets/auth_postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/auth_postgres_password
    volumes:
      - auth_data:/var/lib/postgresql/data

  db_items:
    image: postgres
    secrets:
      - items_postgres_db
      - items_postgres_user
      - items_postgres_password
    restart: always
    expose:
      - "5432"
    networks:
      - portfolio_network
    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_DB=market
#      - POSTGRES_PASSWORD=e5runertuw54u542
      - POSTGRES_USER_FILE=/run/secrets/items_postgres_user
      - POSTGRES_DB_FILE=/run/secrets/items_postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/items_postgres_password
    volumes:
      - items_data:/var/lib/postgresql/data

  db_inventory:
    image: postgres
    secrets:
      - inventory_postgres_db
      - inventory_postgres_user
      - inventory_postgres_password
    restart: always
    expose:
      - "5432"
    networks:
      - portfolio_network
    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_DB=market
#      - POSTGRES_PASSWORD=e5runertuw54u542
      - POSTGRES_USER_FILE=/run/secrets/inventory_postgres_user
      - POSTGRES_DB_FILE=/run/secrets/inventory_postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/inventory_postgres_password
    volumes:
      - inventory_data:/var/lib/postgresql/data

networks:
  portfolio_network:

volumes:
  portfolio_statics:
  middle_earth_statics:
  portfolio_db_data:
  front_data:
  auth_data:
  items_data:
  inventory_data:

secrets:
  portfolio_secret_key:
    external: true
  debug:
    external: true
  aws_access_key:
    external: true
  aws_secret_key:
    external: true
  front_postgres_db:
    external: true
  front_postgres_user:
    external: true
  front_postgres_password:
    external: true
  front_secret_key:
    external: true
  auth_postgres_db:
    external: true
  auth_postgres_user:
    external: true
  auth_postgres_password:
    external: true
  auth_secret_key:
    external: true
  signing_key:
    external: true
  public_key:
    external: true
  items_postgres_db:
    external: true
  items_postgres_user:
    external: true
  items_postgres_password:
    external: true
  items_secret_key:
    external: true
  inventory_postgres_db:
    external: true
  inventory_postgres_user:
    external: true
  inventory_postgres_password:
    external: true
  inventory_secret_key:
    external: true

