# Generated by Django 4.1.3 on 2022-11-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhoOwnsWhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(max_length=128)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=128)),
                ('item_price', models.IntegerField()),
                ('item_description', models.CharField(max_length=1024)),
                ('item_image_url', models.CharField(max_length=1024)),
            ],
        ),
    ]
