# Generated by Django 4.1.3 on 2022-11-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1024)),
                ('wielder_caste', models.CharField(choices=[('WIZARD', 'Wizard'), ('ELF', 'Elf'), ('HUMAN', 'Human'), ('DWARF', 'Dwarf')], max_length=6)),
                ('image_url', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
