FROM nginx:latest
RUN mkdir -p /portfolio/staticfiles
RUN mkdir -p /middle_earth/staticfiles
#COPY conf /etc/nginx/conf.d/default.conf
#uncomment the command below if want to scale up with docker-compose
#COPY conf.d/default.conf /etc/nginx/nginx.conf:ro